version: "3.8"

# define SERVICE block
# one service can startup multi-container
services:
  # define a service named DATABASE
  # [original command]
  # docker run --rm -it --name db -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=some percona
  # docker run --rm -it --link db -p 8080:80 phpmyadmin
  database:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: some

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    links:
      - database:db

  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESSDB_PASSWORD: pass
      WORDPRESS_DB_NAME: some
    ports:
      - 80:80
    links:
      - database:db
